# NumPy
Завдання 


In [96]:
import numpy as np

In [97]:
arr = [
        [1, 2, 3, 4, 5, 6],
        [7, 8, 9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        
    ]   
arr


[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [98]:
arr_np = np.array(arr)
arr_np.shape

(4, 6)

*Задайте розмірність вихідної матриці (наприклад, 4x6)

*Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності
*Виведіть вихідну матрицю.

In [99]:
arr1 = np.arange(1, 25).reshape(4, 6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

- Задайте нові розміри (наприклад, 3x8) і перетворіть матрицю в зазначену форму.
- Виведіть отриману матрицю.

In [100]:
arr2 = np.arange(1, 25).reshape(3, 8)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

- Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.

In [101]:

min_number_row1 = np.min(arr1, axis=1)
min_number_row1


array([ 1,  7, 13, 19])

In [102]:
min_number_row2 = np.min(arr2, axis=1)
min_number_row2

array([ 1,  9, 17])

In [103]:
print(f"arr1: {arr1}")
print(f"arr2: {arr2}")

arr1: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
arr2: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


- Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [104]:
print(f"Sum of arr1: {arr1.sum()}")

Sum of arr1: 300


In [105]:
print(f"Sum of arr2: {arr2.sum()}")

Sum of arr2: 300


## Pandas


### Завдання 

1. Зібрано дані про співробітників та їхні проєкти: "Ім'я", "Проект", "Години".

2. Створіть DataFrame з не менш ніж вісьмома рядками.

3. Виведіть вихідний DataFrame.

In [123]:
import pandas as pd

In [133]:
df = pd.DataFrame({
    'Ім\'я': ['Анна', 'Борис', 'Анна', 'Галина', 'Галина', 'Борис', 'Борис', 'Захар'],
    'Проект': ['Проект A', 'Проект B', 'Проект B', 'Проект D', 'Проект E', 'Проект D', 'Проект D', 'Проект A'],
    'Години': [120, 150, 100, 130, 140, 160, 110, 170]
})
df

,Ім'я,Проект,Години
0,Анна,Проект A,120
1,Борис,Проект B,150
2,Анна,Проект B,100
3,Галина,Проект D,130
4,Галина,Проект E,140
5,Борис,Проект D,160
6,Борис,Проект D,110
7,Захар,Проект A,170


4. Підрахуйте загальну кількість годин за кожним співробітником.

In [134]:
hours_by_name = df.groupby('Ім\'я')['Години'].sum()
hours_by_name

Ім'я
Анна      220
Борис     420
Галина    270
Захар     170
Name: Години, dtype: int64

5. Підрахуйте загальну кількість годин за кожним проєктом.

In [135]:
hours_by_project = df.groupby('Проект')['Години'].sum()
hours_by_project

Проект
Проект A    290
Проект B    250
Проект D    400
Проект E    140
Name: Години, dtype: int64

6. Знайдіть співробітника, який витратив найбільше годин.

In [141]:
employee_index = hours_by_name.idxmax()
employee_index
print(employee_index)
max_hours_employee_index = hours_by_name.max()
print(max_hours_employee_index)
print(f"Співробітник, який витратив найбільше годин: {employee_index} з кількістю годин {max_hours_employee_index}")


Борис
420
Співробітник, який витратив найбільше годин: Борис з кількістю годин 420
