In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

import torch 

In [2]:
a = torch.tensor(1)
a

tensor(1)

In [3]:
b = torch.tensor([1,2,3])
b

tensor([1, 2, 3])

In [5]:
c = torch.tensor([[1,2,3], [4,5,6]])
c

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
arr_tensor = torch.from_numpy(arr)
arr_tensor


tensor([1, 2, 3])

In [8]:
arr[0] = 5

In [9]:
arr_tensor

tensor([5, 2, 3])

In [11]:
from numpy import dtype
from torch import device


a = torch.tensor([1,2,3], dtype=torch.float32, device='cpu')